### ISSUE TITLE
NET Framework support

### ISSUE THREAD

**Issue by Celuni** [wickedlizerd/Pyke#6]
Hello do you plan on making a Nuget build targeting Net Framework?

**Comment by ErikDombi** [comment]
The project is a .NET Standard project so you should be able to use it from a .NET Framework application. What error are you receiving when running it?

**Comment by Celuni** [comment]
```
Could not install package 'Pyke 0.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by ErikDombi** [comment]
Pyke is compiled using .NET Standard 2.1, which .NET Framework does not support.
.NET Framework is no longer developed, and it's recommended you use .NET Core instead.

If .NET Framework is a must for you, you can download the project and compile it yourself for .NET Standard 2.0
